# Generated by Django 5.1.2 on 2024-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_projects_data_added_projects_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_slug',
            field=models.SlugField(default=123, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
