# Generated by Django 5.1.3 on 2024-11-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название места')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.TextField(blank=True, max_length=150, null=True, verbose_name='Тип')),
                ('placement', models.TextField(blank=True, max_length=250, null=True, verbose_name='Расположение')),
                ('price', models.TextField(blank=True, max_length=150, null=True, verbose_name='Расположение')),
                ('rate', models.TextField(blank=True, max_length=150, null=True, verbose_name='Расположение')),
            ],
            options={
                'verbose_name': 'Место размещения',
                'verbose_name_plural': 'Места размещений',
            },
        ),
    ]
