# Generated by Django 5.1.3 on 2024-11-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='shelter_slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='placement',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Месторасположение'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='price',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Стоимость за сутки'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='rate',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Рейтинг'),
        ),
    ]
