# Generated by Django 5.1.3 on 2024-11-12 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_transport_transportphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('type', models.TextField(blank=True, max_length=150, null=True, verbose_name='Тип')),
                ('speed', models.TextField(blank=True, max_length=250, null=True, verbose_name='Месторасположение')),
                ('price', models.TextField(blank=True, max_length=150, null=True, verbose_name='Стоимость')),
                ('rate', models.TextField(blank=True, max_length=150, null=True, verbose_name='Рейтинг')),
                ('fun_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Развлечение',
                'verbose_name_plural': 'Развлечения',
            },
        ),
        migrations.AlterField(
            model_name='transportphoto',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.transport', verbose_name='Транспорт'),
        ),
        migrations.CreateModel(
            name='FunPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='media/fun_photo', verbose_name='Фото')),
                ('fun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fun', verbose_name='Развлечение')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
