# Generated by Django 5.1.3 on 2024-11-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_age_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Фамилия1'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Имя пользователя1'),
        ),
    ]
