# Generated by Django 5.1.3 on 2024-11-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_age_userprofile_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username1',
        ),
    ]
