# Generated by Django 4.2.16 on 2024-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_first_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Mужчина', 'Мужчина'), ('Не мужчина', 'Не мужчина')], null=True, verbose_name='Пол'),
        ),
    ]
